-- Auto Generated SQL Tables --- 

DROP TABLE registry

DROP TABLE elock


DROP SEQUENCE tenant_seq

DROP TABLE tenant

DROP TABLE role


DROP SEQUENCE service_acct_seq

DROP TABLE service_acct


DROP SEQUENCE domain_seq

DROP TABLE domain


DROP SEQUENCE srepo_seq

DROP TABLE srepo

DROP TABLE privilege


DROP SEQUENCE user_seq

DROP TABLE users


DROP SEQUENCE tsnap_seq

DROP TABLE tsnap


DROP SEQUENCE scommit_seq

DROP TABLE scommit


DROP SEQUENCE container_seq

DROP TABLE container


DROP SEQUENCE machine_seq

DROP TABLE machine

DROP TABLE enckeys


DROP SEQUENCE tgroup_seq

DROP TABLE tgroup

DROP TABLE login


DROP SEQUENCE auth_seq

DROP TABLE auth

DROP TABLE ualias

DROP TABLE eprocess

DROP TABLE audit


DROP SEQUENCE eapikey_seq

DROP TABLE eapikey


DROP SEQUENCE blob_fs_seq

DROP TABLE blob_fs

DROP TABLE blob

DROP TABLE cg_reg

DROP TABLE session

