-- Auto Generated SQL Tables --- 

DROP TABLE audit


DROP SEQUENCE auth_seq

DROP TABLE auth

DROP TABLE blob


DROP SEQUENCE blob_fs_seq

DROP TABLE blob_fs

DROP TABLE cg_reg


DROP SEQUENCE container_seq

DROP TABLE container


DROP SEQUENCE domain_seq

DROP TABLE domain


DROP SEQUENCE eapikey_seq

DROP TABLE eapikey

DROP TABLE elock

DROP TABLE enckeys

DROP TABLE eprocess

DROP TABLE login


DROP SEQUENCE machine_seq

DROP TABLE machine

DROP TABLE privilege

DROP TABLE registry

DROP TABLE role


DROP SEQUENCE scommit_seq

DROP TABLE scommit


DROP SEQUENCE service_acct_seq

DROP TABLE service_acct

DROP TABLE session


DROP SEQUENCE srepo_seq

DROP TABLE srepo


DROP SEQUENCE tenant_seq

DROP TABLE tenant


DROP SEQUENCE tgroup_seq

DROP TABLE tgroup


DROP SEQUENCE tsnap_seq

DROP TABLE tsnap

DROP TABLE ualias


DROP SEQUENCE user_seq

DROP TABLE users

